import { Inter,Roboto } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const roboto_init= Roboto({
  subsets:["latin"],
  weight:["100","300","700"],
  variable:'--font-roboto'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}${roboto_init.variable}`}>{children}</body>
    </html>
  );
}
